### PR TITLE
Fix README dependency command

### PR DESCRIPTION
**Pull request by spoeschel**
Adds the necessary precise file name.

### CODE REVIEW

**Comment by skynavga** [comment]
Hi stefan, I'm wondering why you think it necessary to add pom.xml to the directory name on the -f option. It isn't necessary on my installation. Here is what mvn -? says:

<pre>
 -f,--file <arg>                        Force the use of an alternate POM
                                   file (or directory with pom.xml).
</pre>

**Comment by spoeschel** [comment]
Hi Glenn,
this is interesting - it seems that the meaning of `-f` has changed. My version (3.0.5, from the Ubuntu 14.04 LTS packet sources) aborts when I omit the file name. `-?` says:
```
 -f,--file <arg>                        Force the use of an alternate POM
                                        file.
```

**Comment by skynavga** [comment]
I am presently using MVN 3.3.9, though I know it works on earlier 3.3.X
versions.

**Comment by skynavga** [comment]
No action taken.

**Pull request closed without merging**
